version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12

workflows:
  version: 2
  build-and-publish:
    jobs:
      - orb-tools/pack:
          filters:
            branches:
              only: carwow
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - orb-tools/publish:
          name: orb-tools/publish-dev
          orb_name: carwow/queue
          vcs_type: <<pipeline.project.type>>

          requires:
            - orb-tools/pack

          filters:
            branches:
              only: carwow

      - orb-tools/publish:
          orb_name: carwow/queue
          vcs_type: <<pipeline.project.type>>
          pub_type: production

          requires:
            - orb-tools/pack

          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
